// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfsL50QUIWXGt97LrEIUIXgvwyQx8YVhw',
    appId: '1:566314236425:web:2cb0bcd8adb5b32adf16d8',
    messagingSenderId: '566314236425',
    projectId: 'manosexpertas-daf73',
    authDomain: 'manosexpertas-daf73.firebaseapp.com',
    storageBucket: 'manosexpertas-daf73.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4TBOqbgdVq6IexsdHO3XWQ9SISsqgmiQ',
    appId: '1:566314236425:android:b6713714386b9125df16d8',
    messagingSenderId: '566314236425',
    projectId: 'manosexpertas-daf73',
    storageBucket: 'manosexpertas-daf73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlP_xATlW3nF050qHpMxAX94KcCov3a4Y',
    appId: '1:566314236425:ios:d58940aeb7c66d87df16d8',
    messagingSenderId: '566314236425',
    projectId: 'manosexpertas-daf73',
    storageBucket: 'manosexpertas-daf73.firebasestorage.app',
    androidClientId: '566314236425-8puubvpvcffthlemmuj67oud5c0jh8h2.apps.googleusercontent.com',
    iosClientId: '566314236425-bsomp72klvtk504ut6edun7g6qtioc12.apps.googleusercontent.com',
    iosBundleId: 'com.example.manosExpertas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlP_xATlW3nF050qHpMxAX94KcCov3a4Y',
    appId: '1:566314236425:ios:d58940aeb7c66d87df16d8',
    messagingSenderId: '566314236425',
    projectId: 'manosexpertas-daf73',
    storageBucket: 'manosexpertas-daf73.firebasestorage.app',
    androidClientId: '566314236425-8puubvpvcffthlemmuj67oud5c0jh8h2.apps.googleusercontent.com',
    iosClientId: '566314236425-bsomp72klvtk504ut6edun7g6qtioc12.apps.googleusercontent.com',
    iosBundleId: 'com.example.manosExpertas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfsL50QUIWXGt97LrEIUIXgvwyQx8YVhw',
    appId: '1:566314236425:web:296fb6380f1dc0f8df16d8',
    messagingSenderId: '566314236425',
    projectId: 'manosexpertas-daf73',
    authDomain: 'manosexpertas-daf73.firebaseapp.com',
    storageBucket: 'manosexpertas-daf73.firebasestorage.app',
  );

}